name: actividad_3

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9.2'

      - name: Crear entorno virtual
        run: python -m venv venv

      - name: Actualizar pip
        run: python -m pip install --upgrade pip --user

      - name: Instalar dependencias
        run: python -m pip install -e . --user

      - name: Ejecutar script de la actividad 
        run: |
          python -m pip install jupyter nbconvert ipykernel --user
          python -m ipykernel install --user --name=python3
          python -m jupyter nbconvert --to notebook --execute --inplace Actividad/ACTIVIDAD/src/data.ipynb


      - name: Commit and Push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Entrega actividad 3
          commit_user_name: Cristina Guerra [GitHub Actions]
          commit_user_email: elizabeth.guerra@est.iudigital.edu.co
          commit_author: Cristina Guerra <elizabeth.guerra@est.iudigital.edu.co>
